server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  batch:
    jdbc:
      initialize-schema: always

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
batch:
  courier-distance-batch:
    chunk-size: 10
    page-size: 10